### ISSUE TITLE
差分があったときだけ通知

### ISSUE THREAD

**Issue by solaWat** [smknhd-tech/english-class-notify#1]
### 差分があった時だけ通知したいーー

予約可じゃない状態から、予約可になった時のみ通知が来るようにしたい。

**Comment by kwacgit** [comment]
いらなくない?

**Comment by solaWat** [comment]
とりあえず、日付＊時間帯の全てのデータを保持しておく必要がある？
日付が更新されたら、その日付以前のデータは無視する？（変化するのが当然だから）

**Comment by solaWat** [comment]
プログラムに起こす前に、差分とは何なのか（正確には、検知したい差分）を言語化したい。
法則性があるなら書く。
テストが書ければ、一番いいのかもしれない。

**Comment by KAZYPinkSaurus** [comment]
@solaWat 
>プログラムに起こす前に、差分とは何なのか（正確には、検知したい差分）を言語化したい。

[To-Be]
- LINEの最新のコメントを見れば現在の状態がわかる
- 予約状態に変化なし→通知必要なし

つまり
前回の通知からの`差分`

>とりあえず、日付＊時間帯の全てのデータを保持しておく必要がある？
>日付が更新されたら、その日付以前のデータは無視する？（変化するのが当然だから）

↑の実装のためにはすべてのデータ保持の必要はなし
