### ISSUE TITLE
config.txtの内容を変更した際、docker buildをしないと変更が反映されません。

### ISSUE THREAD

**Issue by solaWat** [smknhd-tech/english-class-notify#13]

**Comment by KAZYPinkSaurus** [comment]
これは手間ですね

**Comment by KAZYPinkSaurus** [comment]
--mount の bindが必要?

**Comment by KAZYPinkSaurus** [comment]
Docker関係だし, そらくんに対応してもらいたい😃
これ実装すると設定変更が非常に楽になるので優先順位高めていきたい

**Comment by solWat** [comment]
うーん、やっぱdockerfile内で、ローカルのconfig.txtをコピってきてるのがイケてない感じだねえ。。。
https://qiita.com/tearoom6/items/326895f0a35774d70729#%E3%81%9D%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%8C-image-%E3%81%AB%E5%90%AB%E3%81%BE%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E5%A0%B4%E5%90%88

**Comment by solWat** [comment]
> --mount の bindが必要?

コピらずに、マウント指定した方がいいかもしれないね。
直接コンテナ内に入ってconfig.txt編集する方法はめんどくさいね。
