### ISSUE TITLE
DBの構成を検討します

### ISSUE THREAD

**Issue by solaWat** [smknhd-tech/english-class-notify#9]
まずは、どんなデータを溜めたいのか、から。

- データの種類
- データの質
- データの形式
- データを使ってやりたいこと

**Comment by KAZYPinkSaurus** [comment]
お気に入りの講師が授業をスケジュールを何曜日の何時くらいに開けることが多いかを知りたい｡
何曜日が休みも知りたい｡
e.g. 
講師A : 火曜日は休むことが多く, 大体授業当日の朝にその日の予約をスケジュールを決めがち｡
講師A : 月曜日は休むことが多く, 日曜日の夜に一週間分のスケージュールをまとめて決めがち｡

**Comment by KAZYPinkSaurus** [comment]
講師がレッスンをオープンした曜日と時間を軸にしてこんな感じのグラフにして眺めたい｡
オープンしがちな時間帯, 曜日の可視化をすれば講師毎の傾向を分析できる｡

![image](https://user-images.githubusercontent.com/22516661/85422525-abd5ab80-b5b0-11ea-9538-c0af41b474ef.png)

**Comment by KAZYPinkSaurus** [comment]
基本的に過去の情報はWebページ上から消えてしまうので記録せずに分析はなかなか難しい｡
まず講師名,講師_id,オープン時間のテーブルをつくりたい｡｡｡｡

テーブルを作ることを考えるとdockerなど新たに考えることがうまれてきそう

**Comment by KAZYPinkSaurus** [comment]
イベントが起こるたびに記録して, そこから情報を取り出す と良さそう

例:
オープン時間,クローズ時間｡｡｡

**Comment by KAZYPinkSaurus** [comment]
### テーブル案1
**保存したい属性**
id, 講師名,講師_id,イベント,イベントが起こった日付時間, イベントを起こしたスロットの日付時間(レッスン開始時間とか), サブミットメッセージ

**イベントの想定**
[生徒による予約] 
予約可→予約済 
  
 [レッスン終了] 
予約済→終了    

[生徒による予約キャンセル] 
予約済→予約可  

 [講師によるレッスンオープン] 
空欄→予約可       

[講師によるレッスンクローズ]
予約可→空欄

**Comment by KAZYPinkSaurus** [comment]
### テーブル案2

**保存したい属性**
id, ユーザ名, お気に入り講師id

**Comment by solWat** [comment]
あとで状態遷移の表現方法や正規化について検討する
https://employment.en-japan.com/engineerhub/entry/2018/06/22/110000

**Comment by KAZYPinkSaurus** [comment]
テーブル案1をもう少しシンプルに分ける案
レッスンをオープンした時刻だけ記録していけば, 何時頃オープンしやすいかわかる

###  レッスンをオープンした時間と日付を記録するテーブル
```
講師id unsignint or varcher not null
レッスンの日付 datetime not null
オープンを確認した日付 datetime not null
primary keyは(講師id, レッスンの日付)
```

###  講師テーブル
```
講師id unsignint or varcher not null
講師名 varcher not null
国 varcher not null
primary keyは 講師名
```

**Comment by KAZYPinkSaurus** [comment]
[_φ(･_･]
0始まりの講師IDが存在する
https://eikaiwa.dmm.com/teacher/index/05324/
![image](https://user-images.githubusercontent.com/22516661/99144157-c6670900-26a6-11eb-952c-9e1e5b22e950.png)
